CREATE TABLE reservation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    concert_id BIGINT NOT NULL,
    concert_schedule_seat_id BIGINT NOT NULL,
    reservation_status VARCHAR(50) NOT NULL,
    price BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
